/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6 for MT6795. Copyright MediaTek Inc. (C) 2013.
 * Thu Feb  2 11:50:33 2017
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H


#define AUXADC_TEMPERATURE_CHANNEL     0


#endif //_CUST_AUXADC_TOOL_H


